MvcSeriesPersonajesNT/Models/ErrorViewModel.cs
namespace MvcSeriesPersonajesNT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcSeriesPersonajesNT/Models/Personaje.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcSeriesPersonajesNT.Models
{
    [Table("PERSONAJES")]
    public class Personaje
    {
        [Key]

        [Column("IDPERSONAJE")]
        public int IdPersonaje { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("IDSERIE")]
        public int IdSerie { get; set; }

    }
}

MvcSeriesPersonajesNT/Models/Serie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcSeriesPersonajesNT.Models
{
    [Table("SERIES")]
    public class Serie
    {
        [Key]

        [Column("IDSERIE")]
        public int IdSerie { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("ANYO")]
        public int Anyo { get; set; }
    }
}

MvcSeriesPersonajesNT/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSeriesPersonajesNT.Models;
using System.Diagnostics;

namespace MvcSeriesPersonajesNT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcSeriesPersonajesNT/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSeriesPersonajesNT.Models;
using MvcSeriesPersonajesNT.Repositories;

namespace MvcSeriesPersonajesNT.Controllers
{
    public class SeriesController : Controller
    {
        private RepositorySeries repo;

        public SeriesController(RepositorySeries repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Serie> series = this.repo.GetSeries();
            return View(series);
        }

        public IActionResult Detalles(int id)
        {
            Serie serie = this.repo.FindSerie(id);
            return View(serie);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Serie series)
        {
            this.repo.InsertarSerie(series.IdSerie, series.Nombre, series.Imagen, series.Anyo);
            return RedirectToAction("Index");
        }

        public ActionResult Personajes(int id)
        {
            List<Personaje> personajes = this.repo.GetPersonajes(id);
            return View(personajes);
        }
     
    }
}

MvcSeriesPersonajesNT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">El rincón del seriófilo</h1>
    
</div>

MvcSeriesPersonajesNT/Views/Series/Create.cshtml
@model MvcSeriesPersonajesNT.Models.Serie

@{
    ViewData["Title"] = "Create";
}

<h1>Crear nueva serie:</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anyo" class="control-label"></label>
                <input asp-for="Anyo" class="form-control" />
                <span asp-validation-for="Anyo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcSeriesPersonajesNT/Views/Series/Detalles.cshtml
@model MvcSeriesPersonajesNT.Models.Serie

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles de la serie:</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class="col-sm-10">

            <img class="card-img-top" src="@Model.Imagen" width="100px" />
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anyo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anyo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Volver a la lista</a>
</div>

MvcSeriesPersonajesNT/Views/Series/Index.cshtml
@model IEnumerable<MvcSeriesPersonajesNT.Models.Serie>

@{
    ViewData["Title"] = "Index";
}

<h1>Series TOP</h1>

<p>
    <a asp-controller="Series" asp-action="Create" class="btn btn-outline-info">Crear nueva serie</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anyo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" width="200px"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anyo)
            </td>
            <td>
               <a asp-controller="Series" asp-action="Detalles" asp-route-id="@item.IdSerie"
                   class="btn btn-outline-info"> Detalles</a>

               <a asp-controller="Series" asp-action="Personajes" asp-route-id="@item.IdSerie"
                class="btn btn-outline-success"> Personajes</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcSeriesPersonajesNT/Views/Series/Personajes.cshtml
@model IEnumerable<MvcSeriesPersonajesNT.Models.Personaje>

@{
    ViewData["Title"] = "Personajes";
}

<h1>Personajes principales</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                    <img src="@item.Imagen" width="200px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index">Volver a la lista</a>

MvcSeriesPersonajesNT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcSeriesPersonajesNT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcSeriesPersonajesNT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcSeriesPersonajesNT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">Series Top</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcSeriesPersonajesNT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>